[package]
name = "clok"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
lazy_static = "1.5.0"
ratatui = "0.28.0"
tui-big-text = "0.6.0"
